version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/blogdb
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blogdb
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
